### ISSUE TITLE
vf2-header rewrote

### ISSUE THREAD

**Issue by jonirrings** [orangecms/vf2-loader#1]
thanks for your great work: adapting oreboot for vf2.
I've done the easy part: spl_tool rewrote in Rust
https://github.com/jonirrings/vf2-header

can I transfer it to you, along with `vf2-loader`.

**Comment by orangecms** [comment]
Oh hi, I am so sorry, I hadn't noticed this issue... :sweat_smile: 

We have another implementation of writing that header within oreboot, though we couldn't figure out which CRC variant to use, so we have a full implementation. I'll adapt your findings, thanks you a lot!

And it happens that I spent the last days figuring out what else goes into the header for secure boot:
https://github.com/starfive-tech/Tools/issues/8

That is now so much already, it makes sense to create a library crate. Would you like to help with that? :) 

I have the structs etc here:
https://github.com/orangecms/oreboot/blob/vf2-xtask/xtask/src/starfive/visionfive2_hdr.rs

**Comment by jonirrings** [comment]
nice work
I'll try
